proj_skj1_django/blog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blogger/<int:pk>', views.BlogListbyAuthorView.as_view(), name='blogs-by-author'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('blog/<int:pk>/comment/', views.BlogCommentCreate.as_view(), name='blog_comment'),
]

proj_skj1_django/proj_skj1_django/urls.py
from django.contrib import admin
from django.urls import path

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]

#khlee add 21/02/01
from django.urls import include, path
from rest_framework import routers
from prj1_app import views, urls_prj1App
from django.conf import settings #khlee add 21/02/09
from django.conf.urls.static import static #khlee add 21/02/09
from django.contrib.auth import views as auth_views #khlee add 21/03/01
from django.conf.urls import url #khlee add 21/03/01


admin.site.site_header = 'Code Plane Admin' #khlee add 21/03/11


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'person', views.PersonViewSet)



#khlee add 21/03/06
urlpatterns = [
    path('admin/', admin.site.urls),
]



# Use include() to add URLS from the blog application 
from django.urls import include

urlpatterns += [
#    path('blog/', include('blog.urls')),
]


#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
#    path('', RedirectView.as_view(url='/blog/', permanent=True)),
]



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

from django.views.generic import RedirectView

urlpatterns += [
    
#    path('', include(urls_prj1App)), #khlee add 21/02/17
    
#    path('prj1App_category1/', include(urls_prj1App)), #khlee add 21/02/26
#    path('prj1App_category2/', include(urls_prj1App)), #khlee add 21/02/26
#    path('prj1App_testLink1/', include(urls_prj1App)), #khlee add 21/02/26
#    path('prj1App_testLink2/', include(urls_prj1App)), #khlee add 21/02/26
#    path('prj1App_about/', include(urls_prj1App)), #khlee add 21/02/26
#    path('prj1App_userBlogNew/', include(urls_prj1App)), #khlee add 21/02/26

    
    
    
    #khlee add 21/03/01
    url(r'^accounts/', include('django.contrib.auth.urls')),
    
#    path('', include(router.urls)),
#    path('admin/', admin.site.urls),
    
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
    path('prj1App/', include(urls_prj1App)), #khlee add 21/03/09
    path('summernote/', include('django_summernote.urls')), #khlee add 21/03/14
    url(r'^comments/', include('django_comments_xtd.urls')), #khlee add 21/03/28
    
    path('', RedirectView.as_view(url='/prj1App/', permanent=False)), #khlee add 21/03/09
#    path('', include(urls_prj1App)), #khlee add 21/03/11
        
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj_skj1_django/blog/models.py
from django.db import models

# Create your models here.

from datetime import date
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User #Blog author or commenter



class BlogAuthor(models.Model):
    """
    Model representing a blogger.
    """
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Enter your bio details here.")
    
    class Meta:
        ordering = ["user","bio"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog-author instance.
        """
        return reverse('blogs-by-author', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.user.username


    
    
    
class EntryQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish.true)    
    
    
    
    
class Blog(models.Model):
    """
    Model representing a blog post.
    """
    name = models.CharField(max_length=200)
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because Blog can only have one author/User, but bloggsers can have multiple blog posts.
    description = models.TextField(max_length=60000, help_text="Enter you blog text here.")
    
#    slug = models.SlugField(max_length=201, db_index=True, unique=True, allow_unicode=True)
    publish = models.BooleanField(default=True)
    
#    post_date = models.DateField(default=date.today)
    post_date = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    objects = EntryQuerySet.as_manager()
    
    
    class Meta:
        ordering = ["-post_date"]
    
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name
        
        
class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because BlogComment can only have one author/User, but users can have multiple comments
    post_date = models.DateTimeField(auto_now_add=True)
    blog= models.ForeignKey(Blog, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title=75
        if len(self.description)>len_title:
            titlestring=self.description[:len_title] + '...'
        else:
            titlestring=self.description
        return titlestring



    
    
    
    
    
    

    
    

proj_skj1_django/blog/views.py
from django.shortcuts import render

# Create your views here.


from django.views import generic
from .models import Blog, BlogAuthor, BlogComment
from django.contrib.auth.models import User #Blog author or commenter


def index(request):
    
   # View function for home page of site.
    
    # Render the HTML template index.html
    return render(
        request,
        'index.html',
    )
    


class BlogListView(generic.ListView):
    """
    Generic class-based view for a list of all blogs.
    """
    model = Blog
    paginate_by = 5

    
from django.shortcuts import get_object_or_404

class BlogListbyAuthorView(generic.ListView):
    """
    Generic class-based view for a list of blogs posted by a particular BlogAuthor.
    """
    model = Blog
    paginate_by = 5
    template_name ='blog/blog_list_by_author.html'
    
    def get_queryset(self):
        """
        Return list of Blog objects created by BlogAuthor (author id specified in URL)
        """
        id = self.kwargs['pk']
        target_author=get_object_or_404(BlogAuthor, pk = id)
        return Blog.objects.filter(author=target_author)
        
    def get_context_data(self, **kwargs):
        """
        Add BlogAuthor to context so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(BlogListbyAuthorView, self).get_context_data(**kwargs)
        # Get the blogger object from the "pk" URL parameter and add it to the context
        context['blogger'] = get_object_or_404(BlogAuthor, pk = self.kwargs['pk'])
        return context
    
    

class BlogDetailView(generic.DetailView):
    """
    Generic class-based detail view for a blog.
    """
    model = Blog

    
class BloggerListView(generic.ListView):
    """
    Generic class-based view for a list of bloggers.
    """
    model = BlogAuthor
    paginate_by = 5


from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse


class BlogCommentCreate(LoginRequiredMixin, CreateView):
    """
    Form for adding a blog comment. Requires login. 
    """
    model = BlogComment
    fields = ['description',]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['blog'] = get_object_or_404(Blog, pk = self.kwargs['pk'])
        return context
        
    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.author = self.request.user
        #Associate comment with blog based on passed id
        form.instance.blog=get_object_or_404(Blog, pk = self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self): 
        """
        After posting comment return to associated blog.
        """
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'],})

proj_skj1_django/blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}


<h1>{{ blog.name }}</h1>
<p><strong>Post date</strong> {{ blog.post_date }}</p>


<p><strong>Author:</strong> <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a></p>


<p><strong>Description:</strong></p>
<p style="white-space:pre-wrap;">{{ blog.description }}</p>




<div style="margin-left:20px;margin-top:20px">
<h4>Comments</h4>

{% for comment in blog.blogcomment_set.all %}
<hr>
<p>{{comment.author}} ({{comment.post_date}}) - {{comment.description}}</p>
{% endfor %}
<hr>
{% if user.is_authenticated %}
  <a href="{% url 'blog_comment' blog.id %}">Add a new comment</a></p>
{% else %}
  <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
{% endif %} 


</div>
{% endblock %}

proj_skj1_django/blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All blogs</h1>

    {% if blog_list %}
    <ul>


      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}}) — <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no blogs.</p>
    {% endif %}       
{% endblock %}

proj_skj1_django/blog/templates/blog/blog_list_by_author.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blogger: {{blogger}}</h1>
    
    <h3>Bio</h3>
    
    <p>{{blogger.bio}}</p>
    
    

    {% if blog_list %}
    <h3>Blogs list</h3>
    <ul>

      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}})</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>This blogger hasn't posted anything yet.</p>
    {% endif %}       
{% endblock %}

proj_skj1_django/blog/templates/blog/blogauthor_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All bloggers</h1>

    {% if blogauthor_list %}
    <ul>

       
      {% for author in blogauthor_list %}
      <li>
        <a href="{% url 'blogs-by-author' author.pk %}">{{ author }}</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no bloggers yet.</p>
    {% endif %}       
{% endblock %}

proj_skj1_django/blog/templates/blog/blogcomment_form.html
{% extends "base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blog-detail' blog.pk %}">{{blog.name}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}