proj_skj1_django/blog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blogger/<int:pk>', views.BlogListbyAuthorView.as_view(), name='blogs-by-author'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('blog/<int:pk>/comment/', views.BlogCommentCreate.as_view(), name='blog_comment'),
]

proj_skj1_django/proj_skj1_django/urls.py
from django.contrib import admin
from django.urls import path

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]

#khlee add 21/02/01
from django.urls import include, path
from rest_framework import routers
from prj1_app import views, urls_prj1App
from django.conf import settings #khlee add 21/02/09
from django.conf.urls.static import static #khlee add 21/02/09
from django.contrib.auth import views as auth_views #khlee add 21/03/01
from django.conf.urls import url #khlee add 21/03/01


admin.site.site_header = 'Code Plane Admin' #khlee add 21/03/11


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'person', views.PersonViewSet)



#khlee add 21/03/06
urlpatterns = [
    path('admin/', admin.site.urls),
]



# Use include() to add URLS from the blog application 
from django.urls import include

urlpatterns += [
#    path('blog/', include('blog.urls')),
]


#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
#    path('', RedirectView.as_view(url='/blog/', permanent=True)),
]



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

from django.views.generic import RedirectView

urlpatterns += [
    
#    path('', include(urls_prj1App)), #khlee add 21/02/17
    
#    path('prj1App_category1/', include(urls_prj1App)), #khlee add 21/02/26
#    path('prj1App_category2/', include(urls_prj1App)), #khlee add 21/02/26
#    path('prj1App_testLink1/', include(urls_prj1App)), #khlee add 21/02/26
#    path('prj1App_testLink2/', include(urls_prj1App)), #khlee add 21/02/26
#    path('prj1App_about/', include(urls_prj1App)), #khlee add 21/02/26
#    path('prj1App_userBlogNew/', include(urls_prj1App)), #khlee add 21/02/26

    
    
    
    #khlee add 21/03/01
    url(r'^accounts/', include('django.contrib.auth.urls')),
    
#    path('', include(router.urls)),
#    path('admin/', admin.site.urls),
    
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
    path('prj1App/', include(urls_prj1App)), #khlee add 21/03/09
    path('summernote/', include('django_summernote.urls')), #khlee add 21/03/14
    url(r'^comments/', include('django_comments_xtd.urls')), #khlee add 21/03/28
    
    path('', RedirectView.as_view(url='/prj1App/', permanent=False)), #khlee add 21/03/09
#    path('', include(urls_prj1App)), #khlee add 21/03/11
        
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj_skj1_django/prj1_app/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User #Blog author or commenter


#khlee add 21/02/09
class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    image = models.ImageField(default='media/default_image.jpeg')

    

#khlee add 21/03/03
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    
    
#khlee add 21/03/06
class EntryQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish.true)    

    
#khlee add 21/03/11    
from django.urls import reverse #Used to generate URLs by reversing the URL patterns    
    

class prj1_BlogAuthor(models.Model):
    
    #Model representing a blogger.
    
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Enter your bio details here.")
    
    class Meta:
        ordering = ["user","bio"]

#    def get_absolute_url(self):

        #Returns the url to access a particular blog-author instance.
        
#        return reverse('blogs-by-author', args=[str(self.id)])

    def __str__(self):
        
        #String for representing the Model object.
        
        return self.user.username


from taggit.managers import TaggableManager #khlee add 21/03/20
    
class prj1_Blog(models.Model):
    
    #Model representing a blog post.
    
    title = models.CharField(max_length=200)
    author = models.ForeignKey(prj1_BlogAuthor, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because Blog can only have one author/User, but bloggsers can have multiple blog posts.
    description = models.TextField(max_length=60000, help_text="Enter you blog text here.")
    
#    slug = models.SlugField(max_length=201, db_index=True, unique=True, allow_unicode=True)
    publish = models.BooleanField(default=True)
    
#    post_date = models.DateField(default=date.today)
    post_date = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    objects = EntryQuerySet.as_manager()

    
    tags = TaggableManager(blank=True) #khlee add 21/03/20
    
    class Meta:
        ordering = ["-post_date"]

    def get_absolute_url(self):
        #Returns the url to access a particular blog instance.
        return reverse('prj1App_blog-detail', args=[str(self.id)])

    def __str__(self):
        #String for representing the Model object.
        return self.title
    def contents_summary(self):
        return self.description[:20]
    

    
#khlee add 21/03/11    
class prj1_BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because BlogComment can only have one author/User, but users can have multiple comments
    post_date = models.DateTimeField(auto_now_add=True)
    blog= models.ForeignKey(prj1_Blog, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title=75
        if len(self.description)>len_title:
            titlestring=self.description[:len_title] + '...'
        else:
            titlestring=self.description
        return titlestring    

    
#khlee add 21/03/17    
    
class File(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    author = models.ForeignKey(prj1_BlogAuthor, on_delete=models.SET_NULL, null=True)

    description = models.TextField(max_length=60000, help_text="Enter you blog text here.")
#    slug = models.SlugField(max_length=201, db_index=True, unique=True, allow_unicode=True)
    publish = models.BooleanField(default=True)    
    
    description = models.TextField(blank=True, null=True)
    
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    # file will be saved to MEDIA_ROOT/uploads/2015/01/30
    file = models.FileField(upload_to='uploads/%Y/%m/%d/')
    owner = models.ForeignKey(
        User,
        related_name='owner_files',
        on_delete=models.CASCADE,
    )
    
    tags = TaggableManager(blank=True) #khlee add 21/03/28
    
    def __str__(self):
        return self.title or self.description or self.file.url
    def get_absolute_url(self):
        #Returns the url to access a particular blog-author instance.
        return reverse('download', args=[str(self.id)])
    
    
    
    
class Message(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    files = models.ManyToManyField(
        File,
        blank=True,
        null=True,
        related_name='messages')
    is_read = models.BooleanField(default=False)
    is_public = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    read_date = models.DateTimeField(blank=True, null=True)
    to_users = models.ManyToManyField(User, 'inbox')
    created_by = models.ForeignKey(
        User,
        related_name='sent_inbox_messages',
        on_delete=models.CASCADE,
    )
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)
    def __str__(self):
        return self.title or self.message
    

    
    

proj_skj1_django/prj1_app/forms.py
from django import forms


#khlee add 21/03/03
class LoginForm(forms.Form):
    # LoginForm 에서 입력받을 값은 2개 (아이디, 패스워드)
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)
    
    
    

from .models import prj1_BlogAuthor, prj1_Blog
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


#class CreateBlogForm(forms.Form):
class  CreateBlogForm(forms.ModelForm):
    #title = forms.CharField(max_length=200)
    #author = forms.ModelChoiceField(queryset=prj1_BlogAuthor.objects.all())
      # Foreign Key used because Blog can only have one author/User, but bloggsers can have multiple blog posts.
    #description = forms.CharField(widget=forms.Textarea)
    
        #model = prj1_Blog
        #fields = ['title', 'author', 'description']
        
    #description = forms.CharField(widget=SummernoteWidget()) # iframe으로 적용
    #description = forms.CharField(widget=SummernoteInplaceWidget())
    
    #widgets = {
        #'description': SummernoteWidget(),
    #}
    class Meta:
        model = prj1_Blog
        fields = ['title', 'author', 'description']
        widgets = {
            'description': SummernoteWidget(),
        }

    
    
"""        
class FormFromSModel(forms.ModelForm):
    class Meta:
        model = prj1_Blog
        
        widgets = {
            'description': SummernoteWidget(),
        }
"""            

proj_skj1_django/prj1_app/views.py
from django.shortcuts import render
from .models import Person

# Create your views here.

#khlee add start 21/01/30
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions
from prj1_app.serializers import UserSerializer, GroupSerializer
#from .models import Person #khlee add 21/02/09
from .serializers import PersonSerializer #khlee add 21/02/09
#from . import urls_prj1App #khlee add 21/02/17
from django.views import generic #khlee add 21/03/07
from .models import prj1_Blog, prj1_BlogComment #khlee mod 21/03/11

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]


class PersonViewSet(viewsets.ModelViewSet):
    queryset = Person.objects.all()
    serializer_class = PersonSerializer    

    
#khlee add 21/02/17
#def prj1App_index(request):
#    return render(request, "prj1_app/prj1App_index.html")

#khlee modify 21/03/08

class prj1App_index(generic.ListView):
    model = prj1_Blog
    paginate_by = 5
    template_name ='prj1_app/prj1App_index.html'



#khlee add 21/02/26
def prj1App_category1(request):
    return render(request, "prj1_app/prj1App_category1.html")

def prj1App_category2(request):
    return render(request, "prj1_app/prj1App_category2.html")

def prj1App_testLink1(request):
    return render(request, "prj1_app/prj1App_testLink1.html")

def prj1App_testLink2(request):
    return render(request, "prj1_app/prj1App_testLink2.html")

def prj1App_about(request):
    return render(request, "prj1_app/prj1App_about.html")

#def prj1App_userBlogNew(request):
#    return render(request, "prj1_app/prj1App_userBlogNew.html")




#khlee add 21/03/11
class prj1App_BlogDetailView(generic.DetailView):
    """
    Generic class-based detail view for a blog.
    """
    model = prj1_Blog
    
    


from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse

from django.shortcuts import get_object_or_404


class prj1App_BlogCommentCreate(LoginRequiredMixin, CreateView):
    """
    Form for adding a blog comment. Requires login. 
    """
    model = prj1_BlogComment
    fields = ['description',]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(prj1App_BlogCommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['prj1_blog'] = get_object_or_404(prj1_Blog, pk = self.kwargs['pk'])
        return context
        
    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.author = self.request.user
        #Associate comment with blog based on passed id
        form.instance.blog=get_object_or_404(prj1_Blog, pk = self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(prj1App_BlogCommentCreate, self).form_valid(form)

    def get_success_url(self): 
        """
        After posting comment return to associated blog.
        """
        return reverse('prj1App_blog_comment', kwargs={'pk': self.kwargs['pk'],})


from django.views.generic.edit import CreateView    
from django.contrib.auth.mixins import PermissionRequiredMixin
from django_summernote.widgets import SummernoteWidget #khlee add 21/03/14
from .forms import CreateBlogForm #khlee add 21/03/14


class prj1App_BlogCreate(CreateView): #khlee mod 21/03/17
    template_name = 'prj1_app/prj1_blog_form.html'
    success_url = '/'
    form_class = CreateBlogForm   
#    form = CreateBlogForm()
#    return render(request, "prj1_app/prj1_blog_form.html", {'form': form})


    #model = prj1_Blog
    #fields = ['title', 'author', 'description']
    
    #widgets = {
        #'description': SummernoteWidget(),
    #}
    
    

#khlee add 21/03/17
from .models import File
from django.http import HttpResponse


class prj1App_downloadList(generic.ListView):
    model = File
    paginate_by = 10



#khlee add 21/03/28
class prj1App_downloadListDetail(generic.DetailView):
    model = File
    
    
def download(request, id):
    file = get_object_or_404(File, id=id)
    messages = file.messages.all()
    is_allowed = True if len(list(filter(
        lambda message: (
            request.user in message.to_users.all()
            or
            request.user.username == message.created_by.username
        ),
        messages
    ))) else False
    response = HttpResponse(status=200) #khlee mod 21/03/18
    if not request.headers.get('X-Real-Ip'):
        response.status_code = 404
        response.content = 'The request should be come from Nginx server.'
        return response
    if not is_allowed:
        response.status_code = 403
        response.content = 'You are not allowed to access this file.'
        return response
    file_name = file.file.name
    # Let NGINX handle it
    response['Content-Type'] = ''
    response['X-Accel-Redirect'] = f'{file.file.url}'
#    response['Content-Disposition'] = 'attachment; filename="{}"'.format(file_name)
    return response


#khlee add 21/03/21
class TagCloudTV(generic.TemplateView):
    template_name = 'taggit/taggit_cloud.html'
#    model = prj1_Blog

#    def get_context_data(self, **kwargs):
#        context = super().get_context_data(**kwargs)
#        context['File'] = File.objects.all()
#        return context
    

class TaggedObjectLV(generic.ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = prj1_Blog

    def get_queryset(self):
        return prj1_Blog.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        context['File_object_list'] = File.objects.filter(tags__name=self.kwargs.get('tag'))
        return context
    
    
#khlee add 21/03/25
import json
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def searchData(request):
    qs = ''
    data = ''
    mimetype = ''

    if 'searchinputs' in request.POST:
        print('get post')
        findthis = request.POST['searchinputs']
        print(findthis)
        
        qs = prj1_Blog.objects.all()
        
        if findthis:
            search_qs = qs.filter(title__icontains=findthis)
            result = []
            print(search_qs)
            
            for r in search_qs:
                result.append(r.id)
                result.append(r.title)
            
            data = json.dumps(result)
            print(data)
        else:
            data = 'fail'
        
    mimetype = 'application/json'
    
    return HttpResponse(data,mimetype)

    

proj_skj1_django/prj1_app/templates/prj1_app/file_list.html
{% extends "prj1_base_generic.html" %}
{% load static%}
{%block content%}

<div class="post-card-box">
    <h1>Download list...</h1>
</div>
        
{% if file_list %}




    {% for file in file_list %}
    <div class="post-card-box">
        {{ file.id }}. 
        {%comment%}
        <a href="{% url 'download' file.id %}" class="link-post_list">{{ file.title }} |</a>
        {%endcomment%}
        <a href="{% url 'prj1App_downloadDetail' file.id %}">{{ file.title }} |</a>
        {{ file.upload_date }} | 
        {{ file.author }}
    </div>
    {% endfor %}


{%comment%}

    {% for file in file_list %}
    
        <div class="post-card-box">
                <h2><a href="{{ file.get_absolute_url }}" class="link-post_list">{{ file.title }}</a></h2>
                <p class="post-meta">{{file.upload_date}} | {{ file.author }}</p>
                <div class="post-list-content">내용 공사중...</div>
                <div class="page-tag">
                    <a href="" class="tag" style="color: #faa;">#태그 공사중...</a>
                </div>
        </div>
    {% endfor %}
{%endcomment%}

{% else %}
    <p>There are no download file.</p>
{% endif %}       
{%endblock%}

proj_skj1_django/prj1_app/templates/prj1_app/prj1App_about.html
{% extends "prj1_base_generic.html" %}       
{%block content%}
      
{% load static %}

<div class="small-wrapper">
    <div class="about-container">
        <section class="about-header">
            <div class="author-image-container">
                <img src="{%static 'prj1_app/images/codeplaneLogo.jpg'%}">
            </div>
            <p class="subtitle">STAFF<br> 부산sb 서울kh 인천js</p>
        </section>
        <section class="about-body">
            <ul class="contact-list">

                <li class="email"><a href="mailto:@gmail.com"><i class="fa fa-envelope"></i></a></li>
                {%comment%}
                <li class="phone"><a href="tel:"><i class="fa fa-phone"></i></a></li>
                {%endcomment%}
            </ul>
        </section> <!-- End About Body-->
    </div> <!-- End About Container -->
</div> <!-- End Small Wrapper -->

      
{%endblock%}
{%block pagination%}
{%endblock%}

proj_skj1_django/prj1_app/templates/prj1_app/prj1App_category1.html
{% extends "prj1_base_generic.html" %}

       
{%block content%}
            

    <div class="post-card-box">

        <h2><a href="/node/nodejs-structure/" class="link-post_list">category1 test</a></h2>

        <p class="post-meta">Jun 02, 2019</p>

        <div class="post-list-content">
 
        </div>
        <div class="page-tag">

        <a href="/tags#nodejs" class="tag" style="color: #faa;">#nodejs</a>

        </div>
    </div>

            
{%endblock%}

proj_skj1_django/prj1_app/templates/prj1_app/prj1App_category2.html
{% extends "prj1_base_generic.html" %}

       
{%block content%}
            

    <div class="post-card-box">

        <h2><a href="/node/nodejs-structure/" class="link-post_list">category2 test</a></h2>

        <p class="post-meta">Jun 02, 2019</p>

        <div class="post-list-content">
 
        </div>
        <div class="page-tag">

        <a href="/tags#nodejs" class="tag" style="color: #faa;">#nodejs</a>

        </div>
    </div>

            
{%endblock%}

proj_skj1_django/prj1_app/templates/prj1_app/prj1App_index.html
{% extends "prj1_base_generic.html" %}

       
{%block content%}
            

<div class="post-card-box">
    <h1>Post list...</h1>
</div>


{% if prj1_blog_list %}
    {% for prj1_blog in prj1_blog_list %}
    
        <div class="post-card-box">
                {%comment%}                
                <a href="{{ prj1_blog.get_absolute_url }}">{{ prj1_blog.title }}</a> ({{prj1_blog.post_date}}) — <a href="{% url 'blogs-by-authorblogs-by-author' blog.author.pk %}">{{ prj1_blog.author }}</a>
                {%endcomment%}
                
                <h2><a href="{{ prj1_blog.get_absolute_url }}" class="link-post_list">{{ prj1_blog.title }}</a></h2>
                <p class="post-meta">{{prj1_blog.post_date}} | {{ prj1_blog.author }} <br>{{prj1_blog.contents_summary|safe}}...</p>
            
            
                {%comment%}
                <div class="post-list-content">{{prj1_blog.contents_summary|safe}}...</div>
                {%endcomment%}
            
            
                
                
            
                <div class="page-tag">
                      
                    
                    
                    {% load taggit_templatetags2_tags %} <!--taggit_templatetag2_tags 모듈을 가져온다-->
                
                     
                    {% get_tags_for_object prj1_blog as "tags" %}
                    
                   
                    {% for tag in tags %}
                        <a href="{% url 'tagged_object_list' tag.name %}" class="tag" style="color: #faa;">#{{tag.name}}</a>
                    {% endfor %}

                    
                </div>


        </div>
    {% endfor %}
{% else %}
    <p>There are no blogs.</p>
{% endif %}       


{%endblock%}

proj_skj1_django/prj1_app/templates/prj1_app/prj1App_testLink1.html
{% extends "prj1_base_generic.html" %}

       
{%block content%}
            

    <div class="post-card-box">

        <h2><a href="/node/nodejs-structure/" class="link-post_list">testLink1 test</a></h2>

        <p class="post-meta">Jun 02, 2019</p>

        <div class="post-list-content">
 
        </div>
        <div class="page-tag">

        <a href="/tags#nodejs" class="tag" style="color: #faa;">#nodejs</a>

        </div>
    </div>

            
{%endblock%}

proj_skj1_django/prj1_app/templates/prj1_app/prj1App_userBlogNew.html
{% extends "prj1_base_generic.html" %}    

{% load static %}

{% block header %}


	<meta name="description" content="">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta property="og:image" content="">

    {% load static %}

    <link rel="shortcut icon" href="{%static 'prj1_app/image/codeplaneJustPlaneBOLD.ico'%}" type="image/x-icon">
	<link rel="apple-touch-icon" href="{%static 'prj1_app/image/codeplaneJustPlane.ico'%}">
	<link rel="apple-touch-icon" sizes="72x72" href="{%static 'prj1_app/image/codeplaneJustPlane.ico'%}">
    <link rel="apple-touch-icon" sizes="114x114" href="">
    <!-- Chrome, Firefox OS and Opera -->
	<meta name="theme-color" content="#311e3e">
	<!-- Windows Phone -->
	<meta name="msapplication-navbutton-color" content="#311e3e">
	<!-- iOS Safari -->
	<meta name="apple-mobile-web-app-status-bar-style" content="#311e3e">



    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>


    <!-- Font Awesome -->
	<link rel="stylesheet" href="{%static 'prj1_app/css/all.css'%}">
	<!-- Styles -->
	<link rel="stylesheet" href="{%static 'prj1_app/css/main.css'%}">    

{% endblock %}



{%block content%}
<!--
-->


    <div class="post-card-box">

        <h2>글쓰기</h2>
        <textarea name="content" id="summernote">
        {{ form.content.value|default_if_none:'' }}</textarea>


        <script>
            $('#summernote').summernote({
            placeholder: '여기에 내용 입력하세요~',
            tabsize: 2,
            height: 100
            });
        </script>
        <input type="submit" value="쓴거저장">
    </div>





<!--
<div class="row mt-5">
  <div class="col-12">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">제목</th>
          <th scope="col">아이디</th>
          <th scope="col">작성일</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <th scope="row">1</th>
          <td>제목 테스트 입니다</td>
          <td>member</td>
          <td>2020.12.12</td>
        </tr>
        </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <button class="btn btn-primary">글쓰기</button>
  </div>
    
</div>

-->

<!--
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table> 
    <input type="submit" value="제출">
</form>
-->




{%endblock%}

{%block pagination%}
{% endblock %}

<!--
-->

proj_skj1_django/prj1_app/templates/prj1_app/prj1_blog_list.html
{% extends "prj1_base_generic.html" %}
{%block content%}

    <h1>All blogs</h1>

    {% if prj1_blog_list %}
    <ul>
        
        
      {% for prj1_blog in prj1_blog_list %}
      <li>
        <a href="{{ prj1_blog.get_absolute_url }}">{{ prj1_blog.title }}</a> ({{prj1_blog.post_date}}) — <a href="{% url 'blogs-by-authorblogs-by-author' blog.author.pk %}">{{ prj1_blog.author }}</a>
      </li>
      {% endfor %}

        
    </ul>

    {% else %}
      <p>There are no blogs.</p>
    {% endif %}       
{% endblock %}

proj_skj1_django/prj1_app/templates/prj1_app/prj1_blogcomment_form.html
{% extends "prj1_base_generic.html" %}   
{%block content%}

<p>Post your comment for: <a href="{% url 'prj1App_blog-detail' prj1_blog.pk %}">{{prj1_blog.title}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>

{%endblock%}